### ISSUE TITLE
Running npm test produces AssertionError

### ISSUE THREAD

**Issue by jdsimcoe** [silentrob/harp-editor#2]
Here is the error I get running `npm test`:

``` bash
> harp-editor@0.1.1 test /Users/jdsimcoe/Sites/harp-editor
> mocha --ignore-leaks -t 50000 -R list test

child_process: customFds option is deprecated, use stdio instead.

  1)  "before all" hook

  0 passing (35ms)
  1 failing

  1)  "before all" hook:
     Uncaught AssertionError: missing path
      at Module.require (module.js:363:3)
      at require (module.js:384:17)
      at loadJSON (/Users/jdsimcoe/Sites/harp-editor/lib/editor.js:49:10)
      at loadBoilerPlate (/Users/jdsimcoe/Sites/harp-editor/lib/editor.js:33:18)
      at module.exports (/Users/jdsimcoe/Sites/harp-editor/lib/editor.js:17:12)
      at /Users/jdsimcoe/Sites/harp-editor/test/editor.js:13:36
      at ReadStream.cb (/Users/jdsimcoe/Sites/harp-editor/node_modules/fs-extra/node_modules/ncp/lib/ncp.js:217:38)
      at ReadStream.g (events.js:199:16)
      at ReadStream.emit (events.js:129:20)
      at _stream_readable.js:908:16
      at process._tickCallback (node.js:355:11)



npm ERR! Test failed.  See above for more details.
```

**Comment by silentrob** [comment]
This project has not been maintained. I suspect you will need to roll back to node 0.8.x and try it again.

**Comment by jdsimcoe** [comment]
Makes sense. Thanks!
